name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Se activa solo con pushes a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usa un servidor Linux para construir el proyecto
    steps:
      - name: Checkout âš›ï¸
        uses: actions/checkout@v3 # Descarga tu cÃ³digo al servidor

      - name: Install and Build ğŸ› ï¸
        run: |
          npm install
          npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # La rama donde se guardarÃ¡ el cÃ³digo construido
          folder: dist # La carpeta que se va a desplegar
